# Use a lightweight Ubuntu base image
FROM ubuntu:24.04

ENV LANG=en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV BGD2DEV=/BennuGD2
ENV PATH=${BGD2DEV}/build/linux-gnu/bin:$PATH
ENV LD_LIBRARY_PATH=${BGD2DEV}/build/linux-gnu/bin

# Install dependencies
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        autoconf build-essential cmake make git curl wget unzip \
        ca-certificates binutils zlib1g-dev squashfs-tools \
        libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
        libtheora-dev libogg-dev libvorbis-dev \
        libglu1-mesa-dev libvlc-dev && \
    rm -rf /var/lib/apt/lists/*

# Add build script
ADD build-opk.sh /usr/local/bin/build-opk.sh
RUN chmod +x /usr/local/bin/build-opk.sh

# Clone BennuGD2 source
ARG GIT_BENNUGD2_REPO=https://github.com/SplinterGU/BennuGD2.git
RUN git clone --recursive --depth 1 ${GIT_BENNUGD2_REPO} ${BGD2DEV}

# Build SDL GPU and BennuGD2
WORKDIR ${BGD2DEV}/vendor
RUN ./build-sdl-gpu.sh linux clean && \
    cd ${BGD2DEV} && ./build.sh linux clean

# Set default working directory and shell
WORKDIR /workspace
ENTRYPOINT ["/bin/bash"]
CMD ["-i"]
