# Base image with JDK 17
FROM openjdk:21-jdk-slim

# Android SDK paths
ENV ANDROID_HOME=/opt/android-sdk
ENV ANDROID_NDK_HOME=$ANDROID_HOME/ndk/27.0.12077973
ENV ANDROID_NDK=${ANDROID_NDK_HOME}
ENV PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_NDK_HOME

# Install dependencies and Android command line tools
RUN apt-get update && apt-get install -y wget unzip git curl cmake autoconf automake libtool m4 pkg-config libogg-dev && \
    mkdir -p $ANDROID_HOME/cmdline-tools && \
    cd $ANDROID_HOME/cmdline-tools && \
    # Download and install the command line tools
    wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip && \
    unzip cmdline-tools.zip && \
    mv cmdline-tools latest && \
    rm cmdline-tools.zip && \
    # Accept licenses and install SDK components
    yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses && \
    sdkmanager --sdk_root=${ANDROID_HOME} \
        "platform-tools" \
        "build-tools;34.0.0" \
        "platforms;android-34" \
        "ndk;27.0.12077973" \
        "cmake;3.22.1" && \
    # Clean up
    apt-get clean && rm -rf /var/lib/apt/lists/*

ADD build-android.sh /usr/local/bin/build-android.sh
RUN chmod +x /usr/local/bin/build-android.sh

ADD android_template /opt/android_template

# Clone BennuGD2 source
ENV BGD2DEV=/BennuGD2
ARG GIT_BENNUGD2_REPO=https://github.com/SplinterGU/BennuGD2.git
RUN git clone --recursive --depth 1 ${GIT_BENNUGD2_REPO} ${BGD2DEV}

WORKDIR ${BGD2DEV}
RUN /usr/local/bin/build-android.sh
RUN cd /opt/android_template && \
 mkdir -p app/src/main/jniLibs/arm64-v8a && \
 cp -r /BennuGD2/vendor/android/aarch64-linux-android/arm64-v8a/lib/* app/src/main/jniLibs/arm64-v8a \
 && ./gradlew build

# Default working directory
WORKDIR /workspace
ENTRYPOINT ["/bin/bash"]
CMD ["-i"]