FROM ubuntu:22.04

ENV LANG=en_US.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV BGD2DEV=/BennuGD2
ENV PATH=${BGD2DEV}/build/linux-gnu/bin:$PATH
ENV LD_LIBRARY_PATH=${BGD2DEV}/build/linux-gnu/bin

# Install dependencies
RUN dpkg --add-architecture i386 && \
    apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        gcc-multilib g++-multilib binutils git cmake build-essential unzip \
        ca-certificates binutils zlib1g-dev:i386 squashfs-tools \
        libsdl2-dev:i386 libsdl2-image-dev:i386 libsdl2-mixer-dev:i386 \
        libtheora-dev:i386  libogg-dev:i386 libvorbis-dev:i386 \
        libglu1-mesa-dev:i386 libvlc-dev:i386 && \
    rm -rf /var/lib/apt/lists/*
      
# Clone BennuGD2 source
ARG GIT_BENNUGD2_REPO=https://github.com/SplinterGU/BennuGD2.git
RUN git clone --recursive --depth 1 ${GIT_BENNUGD2_REPO} ${BGD2DEV}

# Build SDL GPU and BennuGD2
WORKDIR ${BGD2DEV}/vendor
RUN ./build-sdl-gpu.sh linux32 clean && \
    cd ${BGD2DEV} && ./build.sh linux32 clean

# Set default working directory and shell
WORKDIR /workspace
ENTRYPOINT ["/bin/bash"]
CMD ["-i"]
