name: CD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update -y && sudo apt install -y zip make

      - name: Build and Package
        run: |
          # Linux build
          make build/linux64
          docker run --rm -v ${{ github.workspace }}:/workspace hldtux/bennugd2-linux64 \
            -c "tar -czvf /workspace/bgd2-linux-x86_64.tar.gz -C /BennuGD2/build/linux-gnu/bin ."

          # Switch build
          make build/switch
          docker run --rm -v ${{ github.workspace }}:/workspace hldtux/bennugd2-switch \
            -c "tar -czvf /workspace/bgd2-switch-aarch64.tar.gz -C /BennuGD2/build/aarch64-none-elf/bin ."

      - name: Upload artifacts Linux
        uses: actions/upload-artifact@v4
        with:
          name: bgd2-linux-x86_64
          path: |
            bgd2-linux-x86_64.tar.gz
      - name: Upload artifacts Switch
        uses: actions/upload-artifact@v4
        with:
          name: bgd2-switch-aarch64
          path: |
            bgd2-switch-aarch64.tar.gz
            
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "*.tar.gz"
