name: CD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

defaults:
  run:
    shell: bash

# required for upload
permissions:
  contents: write

jobs:

  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update -y && sudo apt install -y zip make

      - name: Build
        run: make build/switch

      - name: Compress and Get binaries
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace hldtux/bennugd2-switch \
            -c "tar -czvf /workspace/bgdi-switch-aarch64.tar.gz -C /BennuGD2/build/aarch64-none-elf/bin ."
            
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bgdi-switch-aarch64
          path: bgdi-switch-aarch64.tar.gz

      - name: Build
        run: make build/linux64

      - name: Compress and Get binaries
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace hldtux/bennugd2-linux64 \
            -c "tar -czvf /workspace/bgdi-linux64.tar.gz -C /BennuGD2/build/linux-gnu/bin ."
            
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bgd2-linux-x64_64
          path: bgd2-linux-x64_64.tar.gz


      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.tar.gz
            *.zip