name: CI

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update -y && sudo apt install -y zip make

      - name: Build
        run: make build/linux
