name: deploy-docker

on:
  workflow_dispatch:

jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    environment: DockerHub
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
#          - linux/arm64
        context:
          - linux-x86_64
          - switch-aarch64
          - android-x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set tag name
        run: echo "TAG_NAME=bennugd2-${{ matrix.context }}" >> $GITHUB_ENV

      - name: README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: ${{ secrets.DOCKERHUB_USERNAME }}/bennugd2-${{ env.TAG_NAME }}
          provider: dockerhub
          short_description: 'Docker containers for building BennuGD2 across multiple platforms'
          readme_file: 'README.md'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          platforms: ${{ matrix.platform }}
          push: true
          provenance: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.TAG_NAME }}